### ISSUE TITLE
CC 2015?

### ISSUE THREAD

**Issue by mierla** [smorodsky/radish#3]
I love this extension, but it doesn't seem to work now that I've upgraded to ID CC 2015. The menu items aren't there, and neither is the .versions folder.

**Comment by smorodsky** [comment]
Yes, there are problems with CC2015. Now I do not have time to sort out details. A preliminary study.

## Windows

I hope that the script will work fine after updating Creative Cloud App after 2.1.1.110.

## Mac

Some inserts on applescript not working. They need to rewrite and test. Maybe something else. This will be done not earlier than August. There are chances that Adobe will be repaired applescript in CC2015.

**Comment by mierla** [comment]
Thanks for the reply. After I posted the issue, I did a bit more reading
and learned that Radish certainly isn't the only extension having problems
with CC 2015. Here's hoping Adobe sorts things out on their end!

---

laurenmier@gmail.com
207-215-6523

**Comment by smorodsky** [comment]
Fixed in ID 11.1.0.122
